In [18]:
import pandas as pd
df = pd.read_csv("data_cleaning_sample.csv")
df

       Name   Age         City Gender              Email   Join Date
0     Alice  25.0     New York      F  alice@example.com  01-05-2021
1   Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2       Bob  30.0  Los Angeles      M    bob@example.com         NaN
3   Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4     David  22.0       Mumbai      M  david@example.com  12-11-2019
5       NaN  28.0        Delhi      F     eve@domain.com         NaN
6     Alice  25.0     New York      F  alice@example.com  01-05-2021
7     Alice  25.0     New York      F  alice@example.com  01-05-2021
8   Charlie   NaN        Delhi      M    charlie@example  20-07-2021
9     Alice  25.0     New York      F  alice@example.com  01-05-2021
10    Alice  25.0     New York      F  alice@example.com  01-05-2021
11  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [19]:
df.isnull().sum()

Name         1
Age          4
City         0
Gender       0
Email        0
Join Date    2
dtype: int64

In [20]:
df.dropna(axis=1)

           City Gender              Email
0      New York      F  alice@example.com
1         Delhi      M    charlie@example
2   Los Angeles      M    bob@example.com
3         Delhi      M    charlie@example
4        Mumbai      M  david@example.com
5         Delhi      F     eve@domain.com
6      New York      F  alice@example.com
7      New York      F  alice@example.com
8         Delhi      M    charlie@example
9      New York      F  alice@example.com
10     New York      F  alice@example.com
11        Delhi      M    charlie@example

In [21]:
df.fillna(0)

#is fill the blank data

       Name   Age         City Gender              Email   Join Date
0     Alice  25.0     New York      F  alice@example.com  01-05-2021
1   Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2       Bob  30.0  Los Angeles      M    bob@example.com           0
3   Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4     David  22.0       Mumbai      M  david@example.com  12-11-2019
5         0  28.0        Delhi      F     eve@domain.com           0
6     Alice  25.0     New York      F  alice@example.com  01-05-2021
7     Alice  25.0     New York      F  alice@example.com  01-05-2021
8   Charlie   0.0        Delhi      M    charlie@example  20-07-2021
9     Alice  25.0     New York      F  alice@example.com  01-05-2021
10    Alice  25.0     New York      F  alice@example.com  01-05-2021
11  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [23]:
df.ffill()

df.bfill()

       Name   Age         City Gender              Email   Join Date
0     Alice  25.0     New York      F  alice@example.com  01-05-2021
1   Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2       Bob  30.0  Los Angeles      M    bob@example.com  20-07-2021
3   Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4     David  22.0       Mumbai      M  david@example.com  12-11-2019
5     Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6     Alice  25.0     New York      F  alice@example.com  01-05-2021
7     Alice  25.0     New York      F  alice@example.com  01-05-2021
8   Charlie  25.0        Delhi      M    charlie@example  20-07-2021
9     Alice  25.0     New York      F  alice@example.com  01-05-2021
10    Alice  25.0     New York      F  alice@example.com  01-05-2021
11  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [27]:
#decting and remove duplicate data 

df

df.duplicated()
df.drop_duplicates()


#use 2 column 
df.duplicated(subset=["Name","City"])

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7      True
8      True
9      True
10     True
11     True
dtype: bool

In [29]:
#string op with str
df["Name"].str.lower()

#find the delhi
df["City"].str.contains("delhi",case=False)

0     False
1      True
2     False
3      True
4     False
5      True
6     False
7     False
8      True
9     False
10    False
11     True
Name: City, dtype: bool

In [ ]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")#use the apply



gender_map = {"M": "Male", "F": "Female"}#use for the map
df["Gender"] = df["Gender"].map(gender_map)


df["City"].replace({"Del": "Delhi", "Mum": "Mumbai"})#use for the replace

In [35]:
df

,Name,Age,City,Gender,Email,Join Date,Age Group
0,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult
1,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,Minor
2,Bob,30.0,Los Angeles,Male,bob@example.com,NaN,Adult
3,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,Minor
4,David,22.0,Mumbai,Male,david@example.com,12-11-2019,Adult
5,NaN,28.0,Delhi,Female,eve@domain.com,NaN,Adult
6,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult
7,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult
8,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,Minor
9,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult
10,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult
11,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,Minor