In [10]:
import pandas as pd
#sample data frame 

data = {
    'Name': ['Alic','Sachin','Vicky'],
    'Math': [34,46,67],
    'Science': [77,88,99],
    'English': [98,78,77]

}

df = pd.DataFrame(data)

df

     Name  Math  Science  English
0    Alic    34       77       98
1  Sachin    46       88       78
2   Vicky    67       99       77

In [11]:
#using the melt 
df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")

     Name  Subject  Score
0    Alic     Math     34
1  Sachin     Math     46
2   Vicky     Math     67
3    Alic  Science     77
4  Sachin  Science     88
5   Vicky  Science     99
6    Alic  English     98
7  Sachin  English     78
8   Vicky  English     77

In [18]:
#pivot() — Long to Wide

df_melted = df.melt(id_vars=["Name"], value_vars=["Math","Science","English"],var_name="Subject",value_name="Score")
df_melted

#df_melted.pivot_table(index="Name", columns="Subject", values="Score")

     Name  Subject  Score
0    Alic     Math     34
1  Sachin     Math     46
2   Vicky     Math     67
3    Alic  Science     77
4  Sachin  Science     88
5   Vicky  Science     99
6    Alic  English     98
7  Sachin  English     78
8   Vicky  English     77