In [3]:
#use the marge and join the data 

import pandas as pd 

employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]

})

employees,departments

(   EmpID     Name  DeptID
 0      1    Alice      10
 1      2      Bob      20
 2      3  Charlie      30,
    DeptID     DeptName
 0      10           HR
 1      20  Engineering
 2      40    Marketing)

In [4]:
pd.merge(employees,departments,on="DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [5]:
#left join
pd.merge(employees, departments, on="DeptID", how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [6]:
#Concatenating DataFrames
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [7]:
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})

pd.concat([df1, df2], axis=1)

   ID  Score
0   1     90
1   2     80